trigger:
  batch: true
  branches:
    include:
      - develop
      - qas
      - master
      
pr:
  branches:
    include:
    - '*'  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# DEV

- env:
    VUE_APP_API_URL: $(VUE_APP_API_URL_DEV) 
    VUE_APP_AUTH_URL: $(VUE_APP_AUTH_URL_DEV) 
    VUE_APP_CLIENT_ID: $(VUE_APP_CLIENT_ID_DEV) 
  script: |
    npm install
    npm run build
  displayName: 'DEV - Build'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/dist'
    ArtifactName: 'drop_dev'
    publishLocation: 'Container'
  displayName: 'DEV - Publish drop'

# QAS

- env:
    VUE_APP_API_URL: $(VUE_APP_API_URL_QAS) 
    VUE_APP_AUTH_URL: $(VUE_APP_AUTH_URL_QAS) 
    VUE_APP_CLIENT_ID: $(VUE_APP_CLIENT_ID_QAS)  
  script: |
    npm install
    npm run build
  displayName: 'QAS - Build'
  

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/dist'
    ArtifactName: 'drop_qas'
    publishLocation: 'Container'
  displayName: 'QAS - Publish drop'

  # Production

- env:
    VUE_APP_API_URL: $(VUE_APP_API_URL_PRD) 
    VUE_APP_AUTH_URL: $(VUE_APP_AUTH_URL_PRD) 
    VUE_APP_CLIENT_ID: $(VUE_APP_CLIENT_ID_PRD)  
  script: |
    npm install
    npm run build
  displayName: 'PRD - Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/dist'
    ArtifactName: 'drop_prd'
    publishLocation: 'Container'
  displayName: 'PRD - Publish drop'