variables:
- name: VUE_APP_API_URL
  value: $(VUE_APP_API_URL)
- name: test
  value: asdasdsa

trigger:
  batch: true
  branches:
    include:
      - develop
      - qas
      - master
      
pr:
  branches:
    include:
    - '*'  

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

# DEV

- script: |
    npm install
    npm run build
  displayName: 'DEV - Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/dist'
    ArtifactName: 'drop_dev'
    publishLocation: 'Container'
  displayName: 'DEV - Publish drop'

# QAS

- script: |
    npm install
    npm run build
  displayName: 'QAS - Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/dist'
    ArtifactName: 'drop_qas'
    publishLocation: 'Container'
  displayName: 'QAS - Publish drop'

  # Production

- script: |
    npm install
    npm run build
  displayName: 'PRD - Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/dist'
    ArtifactName: 'drop_prd'
    publishLocation: 'Container'
  displayName: 'PRD - Publish drop'